@startuml
actor User
participant ":Bitbites" as Bitbites
participant ":Parser" as Parser
participant ":HistoryCommand" as HistoryCommand
participant ":FoodList" as FoodList
participant ":UserInterface" as UI

User -> Bitbites : input "history"
activate Bitbites

Bitbites -> Parser : parse("history")
activate Parser
Parser --> Bitbites : HistoryCommand
deactivate Parser

Bitbites -> HistoryCommand : execute(context)
activate HistoryCommand

HistoryCommand -> FoodList : getSummariesByDate()
activate FoodList
FoodList --> HistoryCommand : List<NutritionSummary>
deactivate FoodList

HistoryCommand -> UI : showHistory(summaries)
activate UI
UI --> HistoryCommand
deactivate UI

HistoryCommand --> Bitbites : false
deactivate HistoryCommand

Bitbites --> User
deactivate Bitbites
@enduml
