@startuml
skinparam arrowThickness 1.1
skinparam maxMessageSize 150

participant ":Bitbites" as Bitbites
participant ":Parser" as Parser
participant "c:ListByDateCommand" as ListByDateCommand
participant "foods:FoodList" as FoodList
participant "foodItem:Food" as Food

-> Bitbites : "list d/DATE"
activate Bitbites

Bitbites -> Parser : parse("list d/DATE")
activate Parser

create ListByDateCommand
Parser -> ListByDateCommand : ListByDateCommand("list d/DATE")
activate ListByDateCommand
ListByDateCommand --> Parser : c
deactivate ListByDateCommand

Parser --> Bitbites : c
deactivate Parser

Bitbites -> ListByDateCommand : execute(context)
activate ListByDateCommand

loop for i = 0 to foods.size() - 1
    ListByDateCommand -> FoodList : get(i)
    activate FoodList
    FoodList --> ListByDateCommand : foodItem
    deactivate FoodList

    ListByDateCommand -> Food : getDate()
    activate Food
    Food --> ListByDateCommand : itemDate
    deactivate Food

    opt itemDate.equals(date)
        ListByDateCommand -> ListByDateCommand : System.out.println(foodItem)
    end
end

ListByDateCommand --> Bitbites : isExit = false
deactivate ListByDateCommand

<-- Bitbites
deactivate Bitbites
@enduml
