@startuml
actor User
participant ":Bitbites" as Bitbites
participant ":Parser" as Parser
participant ":ListByDateCommand" as ListByDateCommand
participant ":AppContext" as AppContext
participant ":FoodList" as FoodList
participant ":Food" as Food

User -> Bitbites : input "list d/DATE"
activate Bitbites

Bitbites -> Parser : parse("list d/DATE")
activate Parser
Parser --> Bitbites : ListByDateCommand
deactivate Parser

Bitbites -> ListByDateCommand : execute(context)
activate ListByDateCommand

ListByDateCommand -> AppContext : getFoodList()
activate AppContext
AppContext --> ListByDateCommand : foods
deactivate AppContext

loop [for i = 0 to foods.size() - 1]
  ListByDateCommand -> FoodList : get(i)
  activate FoodList
  FoodList --> ListByDateCommand : foodItem
  deactivate FoodList

  ListByDateCommand -> Food : getDate()
  activate Food
  Food --> ListByDateCommand : itemDate
  deactivate Food

  opt [itemDate.equals(date)]
    ListByDateCommand -> ListByDateCommand : print(foodItem)
    activate ListByDateCommand
    deactivate ListByDateCommand
  end
end

ListByDateCommand --> Bitbites : false
deactivate ListByDateCommand

Bitbites --> User
deactivate Bitbites
@enduml
