@startuml
actor User
participant ":Bitbites" as Bitbites
participant ":Parser" as Parser
participant ":PresetCommand" as PresetCommand
participant ":PresetList" as PresetList
participant "newFood:Food" as Food
participant ":FoodList" as FoodList

User -> Bitbites : input "preset use 1"
activate Bitbites

Bitbites -> Parser : parse("preset use 1")
activate Parser
Parser --> Bitbites : PresetCommand
deactivate Parser

Bitbites -> PresetCommand : execute(context)
activate PresetCommand

PresetCommand -> PresetCommand : handleUse("1", presets, foods)
activate PresetCommand
deactivate PresetCommand

PresetCommand -> PresetList : getPreset(0)
activate PresetList
PresetList --> PresetCommand : template
deactivate PresetList

create Food
PresetCommand -> Food : new Food(name, calories, protein, date)
activate Food
Food --> PresetCommand : newFood
deactivate Food

PresetCommand -> FoodList : addFood(newFood)
activate FoodList
FoodList --> PresetCommand
deactivate FoodList

PresetCommand -> PresetCommand : print "Successfully logged..."
activate PresetCommand
deactivate PresetCommand

PresetCommand --> Bitbites : false
deactivate PresetCommand

Bitbites -> Bitbites : foodStorage.save(foods)
activate Bitbites
deactivate Bitbites

Bitbites --> User
deactivate Bitbites
@enduml
