@startuml
skinparam ArrowFontStyle normal

participant ":Bitbites" as Bitbites
participant "foodStorage:Storage" as FoodStorage
participant "presetStorage:Storage" as PresetStorage
participant "foods:FoodList" as FoodList
participant "fw:FileWriter" as FileWriter

activate Bitbites

Bitbites -> FoodStorage : save(foods)
activate FoodStorage

FoodStorage -> FoodStorage : ensureDirectoryExists()
activate FoodStorage
FoodStorage --> FoodStorage
deactivate FoodStorage

create FileWriter
FoodStorage -> FileWriter : FileWriter("data/foods.txt")
activate FileWriter
FileWriter --> FoodStorage : fw
deactivate FileWriter

loop i < foods.size()
    FoodStorage -> FoodList : getFood(i)
    activate FoodList
    FoodList --> FoodStorage : food
    deactivate FoodList

    FoodStorage -> FileWriter : write(line)
    activate FileWriter
    FileWriter --> FoodStorage
    deactivate FileWriter
end

FoodStorage -> FileWriter : close()
activate FileWriter
FileWriter --> FoodStorage
deactivate FileWriter
destroy FileWriter

FoodStorage --> Bitbites
deactivate FoodStorage

Bitbites -> PresetStorage : save(presets)
activate PresetStorage
note right of PresetStorage: Execution flow is identical\nto foodStorage.save()
PresetStorage --> Bitbites
deactivate PresetStorage

@enduml